version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: football_challenge
      DB_USERNAME: football_challenge
      DB_PASSWORD: football_challenge
    volumes:
      - ./:/var/www/html
    command: ./entrypoint.sh
    expose:
      - 8000
    ports:
      - "8000:8000"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: football_challenge
      MYSQL_ROOT_PASSWORD: football_challenge
      MYSQL_USER: football_challenge
      MYSQL_PASSWORD: football_challenge
